// Frontend/buscador-pisos-frontend/src/components/Buscador.jsx
import { useState, useEffect } from "react";
import axios from "axios";
import {
  Drawer,
  Button,
  Select,
  Stack,
  Text,
  Divider,
  Group,
  RangeSlider,
  NumberInput,
  Checkbox,
  Loader,
  Accordion,
} from "@mantine/core";
import { Coins, Ruler, Star, Settings2 } from "lucide-react";

export default function Buscador({ onResultados, opened, onClose }) {
  const [zonas, setZonas] = useState({});
  const [ciudad, setCiudad] = useState("");
  const [distrito, setDistrito] = useState("");
  const [barrio, setBarrio] = useState("");
  const [operation, setOperation] = useState("rent");
  const [stats, setStats] = useState(null);
  const [priceRange, setPriceRange] = useState([0, 0]);
  const [sizeRange, setSizeRange] = useState([0, 0]);
  const [scoreRange, setScoreRange] = useState([0, 100]);
  const [rooms, setRooms] = useState(null);
  const [floor, setFloor] = useState(null);
  const [hasLift, setHasLift] = useState(false);
  const [loading, setLoading] = useState(false);
  const [noData, setNoData] = useState(false);
  const [loadingZonas, setLoadingZonas] = useState(true);

  // 📦 Cargar jerarquía de zonas desde el backend
  useEffect(() => {
    const cargarZonas = async () => {
      try {
        const res = await axios.get("http://localhost:8000/zonas-jerarquicas");
        console.log("Zonas recibidas:", res.data);
        setZonas(res.data || {});
      } catch (err) {
        console.error("Error cargando zonas:", err);
      } finally {
        setLoadingZonas(false);
      }
    };
    cargarZonas();
  }, []);

  // 🔄 Reset dependientes
  useEffect(() => {
    setDistrito("");
    setBarrio("");
  }, [ciudad]);
  useEffect(() => setBarrio(""), [distrito]);

  // 🔍 Generar selects dinámicos
  const ciudadesOptions =
    Object.keys(zonas || {}).length > 0
      ? Object.keys(zonas).map((c) => ({ value: c, label: c }))
      : [];

  const distritosOptions = ciudad
    ? Object.keys(zonas[ciudad] || {}).map((d) => ({
        value: d,
        label: d,
      }))
    : [];

  const barriosOptions =
    ciudad && distrito
      ? (zonas[ciudad][distrito] || []).map((b) => ({ value: b, label: b }))
      : [];

  // 📊 Cargar estadísticas cuando cambian ciudad/distrito/barrio
  useEffect(() => {
    const cargarStats = async () => {
      const zonaSeleccionada = barrio || distrito || ciudad;
      if (!zonaSeleccionada) return;
      setLoading(true);
      try {
        const res = await axios.get("http://localhost:8000/buscar", {
          params: { ciudad: zonaSeleccionada, operation },
        });
        const props = res.data?.propiedades ?? [];
        const s = res.data?.stats ?? {};
        const rangosValidos =
          s.price &&
          s.size &&
          s.score &&
          (s.price.max > s.price.min ||
            s.size.max > s.size.min ||
            s.score.max > s.score.min);

        if (props.length > 0 && rangosValidos) {
          setStats(s);
          setNoData(false);
          setPriceRange([s.price.min, s.price.max]);
          setSizeRange([s.size.min, s.size.max]);
          setScoreRange([s.score.min, s.score.max]);
        } else {
          setStats(null);
          setNoData(true);
        }
      } catch (err) {
        console.error("Error cargando stats:", err);
        setStats(null);
        setNoData(true);
      } finally {
        setLoading(false);
      }
    };
    cargarStats();
  }, [ciudad, distrito, barrio, operation]);

  // 🔎 Buscar pisos
  const buscarPisos = async () => {
    const zonaSeleccionada = barrio || distrito || ciudad;
    if (!zonaSeleccionada) return alert("Selecciona una zona válida");
    if (noData) return alert("No hay datos disponibles para esta zona");

    try {
      setLoading(true);
      const params = { ciudad: zonaSeleccionada, operation };

      if (stats?.price) {
        params.min_price = priceRange[0];
        params.max_price = priceRange[1];
      }
      if (stats?.size) {
        params.min_size = sizeRange[0];
        params.max_size = sizeRange[1];
      }
      if (stats?.score) {
        params.min_score = scoreRange[0];
        params.max_score = scoreRange[1];
      }
      if (rooms != null) params.rooms = rooms;
      if (floor != null) params.floor = floor;
      if (hasLift) params.hasLift = true;

      const res = await axios.get("http://localhost:8000/buscar", { params });
      onResultados(res.data?.propiedades || [], params);
      onClose();
    } catch (err) {
      alert("Error al buscar pisos: " + err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Drawer
      opened={opened}
      onClose={onClose}
      title={<Text fw={600}>Filtros de búsqueda</Text>}
      position="right"
      size="md"
      overlayProps={{ opacity: 0.4, blur: 3 }}
      zIndex={3000}
    >
      <Stack gap="md" mt="sm">
        {/* Si aún no cargaron las zonas */}
        {loadingZonas ? (
          <Loader color="teal" mt="md" />
        ) : Object.keys(zonas).length === 0 ? (
          <Text c="dimmed" ta="center">
            No hay zonas disponibles.
          </Text>
        ) : (
          <>
            {/* Ciudad */}
            <Select
              label="Ciudad / Municipio"
              placeholder="Selecciona ciudad"
              data={ciudadesOptions}
              value={ciudad}
              onChange={setCiudad}
              searchable
              comboboxProps={{ withinPortal: false }}
            />

            {/* Distrito */}
            <Select
              label="Distrito"
              placeholder="Selecciona distrito"
              data={distritosOptions}
              value={distrito}
              onChange={setDistrito}
              disabled={!ciudad}
              searchable
              comboboxProps={{ withinPortal: false }}
            />

            {/* Barrio */}
            <Select
              label="Barrio"
              placeholder="Selecciona barrio"
              data={barriosOptions}
              value={barrio}
              onChange={setBarrio}
              disabled={!distrito || barriosOptions.length === 0}
              searchable
              comboboxProps={{ withinPortal: false }}
            />
          </>
        )}

        {/* Tipo de operación */}
        <Select
          label="Tipo de operación"
          data={[
            { value: "rent", label: "Alquiler" },
            { value: "sale", label: "Venta" },
          ]}
          value={operation}
          onChange={setOperation}
          searchable
          comboboxProps={{ withinPortal: false }}
        />

        <Divider />

        {loading && <Loader color="teal" size="sm" />}
        {!loading && noData && (
          <Text c="dimmed" ta="center" mt="md">
            No hay datos disponibles para esta zona en{" "}
            {operation === "rent" ? "alquiler" : "venta"}.
          </Text>
        )}

        {!loading && stats && !noData && (
          <>
            <Group justify="center" gap={6}>
              <Coins size={18} />
              <Text fw={500}>Precio (€)</Text>
            </Group>
            <RangeSlider
              min={stats.price.min}
              max={stats.price.max}
              step={50}
              value={priceRange}
              onChange={setPriceRange}
            />

            <Group justify="center" gap={6}>
              <Ruler size={18} />
              <Text fw={500}>Tamaño (m²)</Text>
            </Group>
            <RangeSlider
              min={stats.size.min}
              max={stats.size.max}
              step={5}
              value={sizeRange}
              onChange={setSizeRange}
            />

            <Group justify="center" gap={6}>
              <Star size={18} />
              <Text fw={500}>Score (0–100)</Text>
            </Group>
            <RangeSlider
              min={stats.score.min}
              max={stats.score.max}
              step={5}
              value={scoreRange}
              onChange={setScoreRange}
            />

            <Accordion mt="md" variant="separated" radius="md">
              <Accordion.Item value="advanced">
                <Accordion.Control icon={<Settings2 size={18} />}>
                  Filtros avanzados
                </Accordion.Control>
                <Accordion.Panel>
                  <Stack gap="sm" mt="xs">
                    <NumberInput
                      label="Habitaciones mínimas"
                      value={rooms}
                      onChange={setRooms}
                      min={0}
                    />
                    <NumberInput
                      label="Planta"
                      value={floor}
                      onChange={setFloor}
                      min={0}
                    />
                    <Divider />
                    <Checkbox
                      label="Ascensor"
                      checked={hasLift}
                      onChange={(e) =>
                        setHasLift(e.currentTarget.checked)
                      }
                    />
                  </Stack>
                </Accordion.Panel>
              </Accordion.Item>
            </Accordion>
          </>
        )}

        <Divider />

        <Group justify="flex-end" mt="md">
          <Button variant="light" color="gray" onClick={onClose}>
            Cancelar
          </Button>
          <Button
            color="teal"
            onClick={buscarPisos}
            disabled={loading || !ciudad || noData}
          >
            {loading ? "Buscando..." : "Buscar"}
          </Button>
        </Group>
      </Stack>
    </Drawer>
  );
}

// Frontend_Ang/src/app/shared/features/mapa/buscador/buscador.component.ts
import { Component, EventEmitter, Input, Output, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DrawerShellComponent } from '../../../../shared/components/drawer-shell/drawer-shell.component';
import { LucideAngularModule } from 'lucide-angular';
import { BusquedaService } from '../../../../core/services/busqueda.service';
import { ZonasService } from '../../../../core/services/zonas.service';
import { FiltroBusqueda } from '../../../../core/models/filtros.model';
import { Propiedad } from '../../../../core/models/propiedad.model';

@Component({
  selector: 'app-buscador',
  standalone: true,
  imports: [CommonModule, FormsModule, DrawerShellComponent, LucideAngularModule],
  templateUrl: './buscador.component.html',
  styleUrls: ['./buscador.component.scss'],
})
export class BuscadorComponent implements OnChanges {
  @Input() opened = false;
  @Output() openedChange = new EventEmitter<boolean>();
  @Output() resultados = new EventEmitter<{ pisos: Propiedad[]; filtros: FiltroBusqueda }>();

  // Estado
  zonas: Record<string, any> = {};
  ciudad = '';
  distrito = '';
  barrio = '';
  operation: 'sale' | 'rent' = 'rent';
  priceRange = [0, 0];
  sizeRange = [0, 0];
  scoreRange = [0, 100];
  rooms: number | null = null;
  floor: number | null = null;
  hasLift = false;
  loading = false;
  loadingZonas = true;
  noData = false;
  stats: any = null;

  constructor(private busqueda: BusquedaService, private zonasSrv: ZonasService) {}

  async ngOnChanges(changes: SimpleChanges) {
    if (changes['opened'] && this.opened) {
      await this.cargarZonas();
    }
  }

  async cargarZonas() {
    this.loadingZonas = true;
    try {
      this.zonas = await this.zonasSrv.getZonasJerarquicas().toPromise();
    } catch (err) {
      console.error('Error cargando zonas', err);
      this.zonas = {};
    } finally {
      this.loadingZonas = false;
    }
  }

  get ciudadesOptions() {
    return Object.keys(this.zonas || {}).map((c) => c);
  }

  get distritosOptions() {
    return this.ciudad ? Object.keys(this.zonas[this.ciudad] || {}) : [];
  }

  get barriosOptions() {
    return this.ciudad && this.distrito ? this.zonas[this.ciudad][this.distrito] || [] : [];
  }

  resetDependientes() {
    this.distrito = '';
    this.barrio = '';
  }

  async cargarStatsZona() {
    const zonaSeleccionada = this.barrio || this.distrito || this.ciudad;
    if (!zonaSeleccionada) return;

    this.loading = true;
    try {
      const res = await this.busqueda.buscar({ ciudad: zonaSeleccionada, operation: this.operation }).toPromise();
      const s = (res as any)?.stats || {};
      this.stats = s;

      if (s.price && s.size && s.score) {
        this.priceRange = [s.price.min, s.price.max];
        this.sizeRange = [s.size.min, s.size.max];
        this.scoreRange = [s.score.min, s.score.max];
        this.noData = false;
      } else {
        this.noData = true;
      }
    } catch (err) {
      console.error('Error cargando stats:', err);
      this.noData = true;
    } finally {
      this.loading = false;
    }
  }

  async buscarPisos() {
    const zonaSeleccionada = this.barrio || this.distrito || this.ciudad;
    if (!zonaSeleccionada) {
      alert('Selecciona una zona válida');
      return;
    }

    const filtros: FiltroBusqueda = {
      ciudad: zonaSeleccionada,
      operation: this.operation,
      min_price: this.priceRange[0],
      max_price: this.priceRange[1],
      min_size: this.sizeRange[0],
      max_size: this.sizeRange[1],
      min_score: this.scoreRange[0],
      max_score: this.scoreRange[1],
      rooms: this.rooms ?? undefined,
      floor: this.floor ?? undefined,
      hasLift: this.hasLift,
    };

    try {
      this.loading = true;
      const pisos = await this.busqueda.buscarTodasPaginas(filtros);
      this.resultados.emit({ pisos, filtros });
      this.opened = false;
      this.openedChange.emit(false);
    } catch (err) {
      const e = err as Error;
      alert('Error al buscar pisos: ' + e.message);
    } finally {
      this.loading = false;
    }
  }

  async mostrarTodos() {
    try {
      this.loading = true;
      const res = await this.busqueda.buscarTodo(this.operation).toPromise();
      const pisos = (res as any)?.propiedades ?? [];
      this.resultados.emit({ pisos, filtros: { operation: this.operation, mostrarTodo: true } });
      this.opened = false;
      this.openedChange.emit(false);
    } catch (err) {
      const e = err as Error;
      alert('Error al cargar todos los datos: ' + e.message);
    } finally {
      this.loading = false;
    }
  }

  onOpenedChange(value: boolean) {
    this.opened = value;
    this.openedChange.emit(value);
  }
}

<app-drawer-shell
  [(opened)]="opened"
  (openedChange)="onOpenedChange($event)"
  [title]="'Filtros de búsqueda'"
  position="right"
  [width]="'520px'"
  [loading]="loadingZonas"
>
  <div drawer-content>
    <!-- Selects jerárquicos -->
    <div class="select-group">
      <label>Ciudad / Municipio</label>
      <select [(ngModel)]="ciudad" (change)="resetDependientes(); cargarStatsZona()">
        <option [ngValue]="''">Selecciona ciudad</option>
        <option *ngFor="let c of ciudadesOptions" [value]="c">{{ c }}</option>
      </select>

      <label>Distrito</label>
      <select [(ngModel)]="distrito" (change)="barrio = ''; cargarStatsZona()" [disabled]="!ciudad">
        <option [ngValue]="''">Selecciona distrito</option>
        <option *ngFor="let d of distritosOptions" [value]="d">{{ d }}</option>
      </select>

      <label>Barrio</label>
      <select [(ngModel)]="barrio" (change)="cargarStatsZona()" [disabled]="!distrito">
        <option [ngValue]="''">Selecciona barrio</option>
        <option *ngFor="let b of barriosOptions" [value]="b">{{ b }}</option>
      </select>
    </div>

    <!-- Tipo de operación -->
    <div class="select-group">
      <label>Tipo de operación</label>
      <select [(ngModel)]="operation" (change)="cargarStatsZona()">
        <option value="rent">Alquiler</option>
        <option value="sale">Venta</option>
      </select>
    </div>

    <!-- Rangos -->
    <div *ngIf="stats && !noData" class="rango">
      <label>💶 Precio (€)</label>
      <input type="range" [(ngModel)]="priceRange[0]" [min]="stats.price.min" [max]="stats.price.max" />
      <input type="range" [(ngModel)]="priceRange[1]" [min]="stats.price.min" [max]="stats.price.max" />

      <label>📏 Tamaño (m²)</label>
      <input type="range" [(ngModel)]="sizeRange[0]" [min]="stats.size.min" [max]="stats.size.max" />
      <input type="range" [(ngModel)]="sizeRange[1]" [min]="stats.size.min" [max]="stats.size.max" />

      <label>⭐ Score (0–100)</label>
      <input type="range" [(ngModel)]="scoreRange[0]" [min]="stats.score.min" [max]="stats.score.max" />
      <input type="range" [(ngModel)]="scoreRange[1]" [min]="stats.score.min" [max]="stats.score.max" />
    </div>

    <!-- Avanzado -->
    <div class="advanced">
      <h4>Filtros avanzados</h4>
      <label>Habitaciones mínimas</label>
      <input type="number" [(ngModel)]="rooms" min="0" />

      <label>Planta mínima</label>
      <input type="number" [(ngModel)]="floor" min="0" />

      <label>
        <input type="checkbox" [(ngModel)]="hasLift" /> Ascensor
      </label>
    </div>
  </div>

  <!-- Footer -->
  <div drawer-footer>
    <div class="footer-actions">
      <button class="secondary" (click)="opened = false; openedChange.emit(false)">Cancelar</button>
      <button class="secondary" (click)="mostrarTodos()">Mostrar todos</button>
      <button class="primary" (click)="buscarPisos()" [disabled]="loading || noData">Buscar</button>
    </div>
  </div>
</app-drawer-shell>
