// Frontend_Ang/src/app/shared/features/mapa/drawer-favoritos/drawer-favoritos.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DrawerShellComponent } from '../../../components/drawer-shell/drawer-shell.component'; 
import { FavoritosService } from '../../../../core/services/favoritos.service'; 
import { LucideAngularModule } from 'lucide-angular';
import { Propiedad } from '../../../../core/models/propiedad.model';

@Component({
  selector: 'app-drawer-favoritos',
  standalone: true,
  imports: [CommonModule, DrawerShellComponent, LucideAngularModule],
  templateUrl: './drawer-favoritos.component.html',
  styleUrls: ['./drawer-favoritos.component.scss'],
})
export class DrawerFavoritosComponent {
  /** Control externo de apertura del drawer */
  @Input() opened = false;
  @Output() openedChange = new EventEmitter<boolean>();

  constructor(public favoritos: FavoritosService) {}

  toggleDrawer(open: boolean) {
    this.opened = open;
    this.openedChange.emit(this.opened); 
  }

  quitarFavorito(piso: Propiedad) {
    this.favoritos.toggleFavorito(piso);
  }

  borrarTodos() {
    this.favoritos.borrarTodos();
  }
  onClose() {
    this.opened = false;
    this.openedChange.emit(false);
  }
  onOpenedChange(value: boolean) {
    this.opened = value;
    this.openedChange.emit(value);
  }
}

<app-drawer-shell
  [(opened)]="opened"
  (openedChange)="onOpenedChange($event)"
  [title]="'Mis pisos favoritos ❤️'"
  position="right"
  [width]="'460px'"
>
  <!-- Contenido -->
  <div drawer-content>
    <ng-container *ngIf="(favoritos.favoritos$ | async) as lista">
      <p *ngIf="lista.length === 0" class="empty-msg">
        No tienes pisos guardados aún.
      </p>

      <div *ngFor="let p of lista" class="favorito-item">
        <div class="info">
          <h4>{{ p.address || 'Dirección desconocida' }}</h4>
          <p class="detalle">
            {{ p.price ? (p.price | number) + ' €' : 'Sin precio' }} —
            {{ p.size ? p.size + ' m²' : 'Sin tamaño' }}
          </p>
          <a
            *ngIf="p.url"
            [href]="p.url"
            target="_blank"
            rel="noopener noreferrer"
            >Ver en Idealista</a
          >
        </div>

        <button class="remove-btn" (click)="quitarFavorito(p)">
          <lucide-icon name="trash-2"></lucide-icon>
          Quitar
        </button>
      </div>
    </ng-container>
  </div>

  <!-- Footer -->
  <div drawer-footer>
    <button class="clear-btn" (click)="borrarTodos()">
      <lucide-icon name="trash"></lucide-icon>
      Borrar todos
    </button>
  </div>
</app-drawer-shell>

// Frontend/buscador-pisos-frontend/src/components/DrawerFavoritos.jsx
import { Drawer, ScrollArea, Stack, Box, Text, Group, Button, Divider } from "@mantine/core";
import { useFavoritos } from "../context/FavoritosContext";


export default function DrawerFavoritos({ opened, onClose }) {
  const { favoritos, toggleFavorito, borrarTodos } = useFavoritos();

  return (
    <Drawer
      opened={opened}
      onClose={onClose}
      title={<Text fw={600}>Mis pisos favoritos ❤️</Text>}
      position="right"
      size="md"
      overlayProps={{ opacity: 0.4, blur: 3 }}
      withinPortal={false}
      zIndex={99999}
    >
      {favoritos.length === 0 ? (
        <Text c="dimmed" ta="center" mt="lg">
          No tienes pisos guardados aún.
        </Text>
      ) : (
        <ScrollArea h="calc(100vh - 140px)">
          <Stack gap="sm">
            {favoritos.map((p) => (
              <Box
                key={p.propertyCode}
                p="sm"
                style={{
                  border: "1px solid #ccc",
                  borderRadius: "8px",
                  background: "var(--mantine-color-body)",
                }}
              >
                <Group justify="space-between">
                  <div>
                    <Text fw={500}>{p.address || "Dirección desconocida"}</Text>
                    <Text size="sm" c="dimmed">
                      {p.price ? `${p.price.toLocaleString()} €` : "Sin precio"} —{" "}
                      {p.size ? `${p.size} m²` : "Sin tamaño"}
                    </Text>
                    {p.url && (
                      <a
                        href={p.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{ color: "#228be6", fontSize: "0.9em" }}
                      >
                        Ver en Idealista
                      </a>
                    )}
                  </div>

                  <Button
                    color="red"
                    size="xs"
                    variant="light"
                    onClick={() => toggleFavorito(p)}
                  >
                    Quitar
                  </Button>
                </Group>
              </Box>
            ))}
          </Stack>
        </ScrollArea>
      )}

      <Divider my="md" />
      <Group justify="flex-end">
        <Button variant="light" color="red" onClick={borrarTodos}>
          Borrar todos
        </Button>
      </Group>
    </Drawer>
  );
}
